sudo: required

language: go
go:
  - 1.5

services:
  - docker

before_install:
  - docker run -d --name mongo -p 27017:27017 mongo

install:
  - go get github.com/InteractiveLecture/middlewares/jwtware
  - go get github.com/InteractiveLecture/middlewares/groupware
  - go get github.com/gorilla/mux
  - go get github.com/satori/go.uuid
  - go get gopkg.in/mgo.v2
  - go get  github.com/stretchr/testify/assert

before_script:
  - sleep 15

script:
  - ./build.sh
